#!/usr/bin/env node
// scripts/count-skills.mjs
// Authoritative skill counter + documentation consistency guard.
//
// Source of truth: csp-router/registry.json (regenerated by `npm run build:registry`).
// This script reports the canonical skill count and verifies that every place
// the number is hard-coded in docs/README/CLAUDE.md agrees with it.
//
// Usage:
//   node scripts/count-skills.mjs           # report + check, exit 1 on mismatch
//   node scripts/count-skills.mjs --quiet   # only print on mismatch
//
// Wire into CI so a stale number fails the build instead of shipping.

import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const quiet = process.argv.includes('--quiet');

// --- 1. Canonical count from registry.json ---
const registryPath = join(ROOT, 'csp-router', 'registry.json');
if (!existsSync(registryPath)) {
  console.error('❌ registry.json not found. Run `npm run build:registry` first.');
  process.exit(1);
}
const registry = JSON.parse(readFileSync(registryPath, 'utf8'));
const canonical = registry.skills.length;

if (registry.total_skills !== canonical) {
  console.error(`❌ registry.json internal mismatch: total_skills=${registry.total_skills} but skills[]=${canonical}. Run \`npm run build:registry\`.`);
  process.exit(1);
}

// --- 2. Files that hard-code the count, and how to find stale numbers ---
// Each entry: file path + a regex whose every match's captured group must equal `canonical`.
const checks = [
  { file: 'CLAUDE.md',                 re: /Total:\s*(\d+)\s+skills/g },
  { file: 'README.md',                 re: /badge\/skills-(\d+)-/g },
  { file: 'README.md',                 re: /·\s*(\d+)\s+Skills?\b/g },
  { file: 'README.md',                 re: /^(\d+)\s+skills distributed/gm },
  { file: 'README.md',                 re: /Total:\s*(\d+)\s+skills/g },
  { file: 'README.md',                 re: /all\s+(\d+)\s+skills\b/g },
  { file: 'README_zh.md',              re: /badge\/skills-(\d+)-/g },
  { file: 'README_zh.md',              re: /·\s*(\d+)\s*个技能/g },
  { file: 'README_zh.md',              re: /^(\d+)\s*个技能分布/gm },
  { file: 'README_zh.md',              re: /全部\s*(\d+)\s*个/g },
  { file: 'README_zh.md',              re: /总计：(\d+)\s*个技能/g },
  { file: 'docs/SKILL-INDEX.md',       re: /状态：(\d+)\s*个技能/g },
];

const mismatches = [];
for (const { file, re } of checks) {
  const p = join(ROOT, file);
  if (!existsSync(p)) continue;
  const text = readFileSync(p, 'utf8');
  let m;
  re.lastIndex = 0;
  while ((m = re.exec(text)) !== null) {
    const found = Number(m[1]);
    if (found !== canonical) {
      mismatches.push({ file, found, expected: canonical, snippet: m[0] });
    }
  }
}

// --- 3. Report ---
if (!quiet || mismatches.length) {
  console.log(`📊 Canonical skill count (registry.json): ${canonical}`);
  console.log(`   version: ${registry.version}`);
}

if (mismatches.length) {
  console.error(`\n❌ ${mismatches.length} stale skill-count reference(s) found:`);
  for (const mm of mismatches) {
    console.error(`   ${mm.file}: found "${mm.snippet}" → expected ${mm.expected}`);
  }
  console.error('\nFix: update the numbers above, or regenerate docs. registry.json is the source of truth.');
  process.exit(1);
}

if (!quiet) console.log('✅ All documented skill counts match the registry.');
